### ISSUE TITLE
关于买手接单接口的几点疑问

### ISSUE THREAD

**Issue by beautifulSoup** [wangtZJU/laifu#3]
![image](https://cloud.githubusercontent.com/assets/5506713/8692564/ff21b908-2b01-11e5-95a5-1b63065bd9b0.png) 
想order_type， 这种本身就是int类型的值，不要返回String比较好吧。
pay这个值在Json里面用num类型的，但是本身应该是double类型，所以还是写成0.00这种方式比较好吧。

**Comment by wangdai** [comment]
pay在模型里是decimal，这个显然对应的是字符串比较科学，不会损失精度。。。

**Comment by wangdai** [comment]
其他该是int的类型都改成int了
fix in https://github.com/wangtZJU/laifu/commit/a7dd043e7f81cb26344e184a1a3146fed27665bf
